"""empty message

Revision ID: 1dc545c67cd7
Revises: None
Create Date: 2015-04-03 22:02:25.403691

"""

# revision identifiers, used by Alembic.
revision = '1dc545c67cd7'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy import DefaultClause

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('vulgar', sa.Integer(), nullable=False, server_default=DefaultClause("0")))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'vulgar')
    ### end Alembic commands ###
