"""empty message

Revision ID: 510117935dc0
Revises: 1dc545c67cd7
Create Date: 2015-04-04 16:59:19.157990

"""

# revision identifiers, used by Alembic.
revision = '510117935dc0'
down_revision = '1dc545c67cd7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import DefaultClause

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('want_vulgar', sa.Integer(), nullable=False, server_default=DefaultClause("0")))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'want_vulgar')
    ### end Alembic commands ###
